pub fn reverse_map(n: f64) -> (u16, u16) {
    let index = (n * u32::MAX as f64) as u32;

    // deinterleave bits
    let mut x: u16 = 0;
    let mut y: u16 = 0;

    for i in 0..16 {
        // even bits -> x
        let x_bit = ((index >> (2 * i)) & 1) as u16;
        x |= x_bit << i;

        // odd bits -> y
        let y_bit = ((index >> (2 * i + 1)) & 1) as u16;
        y |= y_bit << i;
    }
    (x, y)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ex10::map;

    #[test]
    fn test_f_inverse_f() {
        // (f⁻¹ ∘ f)(x, y) = (x, y)
        // This is always perfect because every (x, y) is a valid input.
        let test_points = vec![
            (0, 0),
            (100, 200),
            (u16::MAX, u16::MAX),
            (12345, 54321),
            (1, 0),
            (0, 1),
        ];

        for (x, y) in test_points {
            let z = map(x, y);
            let (x_recovered, y_recovered) = reverse_map(z);

            assert_eq!(
                (x_recovered, y_recovered),
                (x, y),
                "Failed perfect identity for ({}, {})",
                x,
                y
            );
        }
    }

    #[test]
    fn test_f_of_f_inverse_exact() {
        // (f ∘ f⁻¹)(z) = z
        // We only test values that are DEFINED in the set A.
        // These are the exact results of mapping specific (x, y) pairs.
        let exact_values = vec![
            map(0, 0),         // 0.0
            map(65535, 65535), // 1.0
            map(100, 200),     // 0.000010762363674762278...
            map(1, 2),         // 0.0000000020954757933727176...
            map(12345, 54321), // 0.6528329410713243...
        ];

        for z in exact_values {
            let (x, y) = reverse_map(z);
            let z_recovered = map(x, y);

            // Since z was generated by map, it MUST be perfectly reversible
            // to the exact same bit pattern in f64.
            assert_eq!(
                z.to_bits(),
                z_recovered.to_bits(),
                "Bit-level mismatch for z = {}",
                z
            );
        }
    }

    #[test]
    fn test_dense_bijectivity() {
        // Checking every point in a 256x256 block to ensure no two points collide
        // and every point returns to its origin.
        for x in 0..256u16 {
            for y in 0..256u16 {
                let z = map(x, y);
                let (rx, ry) = reverse_map(z);
                assert_eq!((x, y), (rx, ry));
            }
        }
    }
}
