/// Inverse of the Z-order (Morton) space-filling curve mapping.
///
/// Given a normalized value in [0, 1], reconstructs the original 2D coordinates
/// that produced it via the `map` function in ex10. This implements the bijection
/// $f^{-1}: [0,1] \to \{0, 1, \ldots, 65535\}^2$.
///
/// # Arguments
///
/// * `n` - A normalized value in [0, 1] (typically the output of `map(x, y)`)
///
/// # Returns
///
/// A tuple `(x, y)` where both coordinates are in the range [0, 65535]
///
/// # Algorithm
///
/// 1. **Denormalize**: Multiply by `u32::MAX` and round to recover the 32-bit Morton index
/// 2. **De-interleave bits**: Extract alternating bits:
///    - Even bit positions (0, 2, 4, ..., 30) → x coordinate
///    - Odd bit positions (1, 3, 5, ..., 31) → y coordinate
/// 3. **Reconstruct**: Build x and y by shifting extracted bits into place
///
/// # Mathematical Properties
///
/// - **Left Inverse**: $(f^{-1} \circ f)(x, y) = (x, y)$ for all valid $(x, y)$
/// - **Right Inverse**: $(f \circ f^{-1})(n) \approx n$ when $n$ is in the range of $f$
/// - **Bijectivity**: Together with `map`, forms a bijection between discrete grid and continuous interval
///
/// # Examples
///
/// ```
/// use ex10::map;
/// use ex11::reverse_map;
///
/// // Perfect round-trip for coordinates
/// let (x, y) = (12345, 54321);
/// let z = map(x, y);
/// let (rx, ry) = reverse_map(z);
/// assert_eq!((x, y), (rx, ry));
///
/// // Inverse at boundaries
/// assert_eq!(reverse_map(0.0), (0, 0));
/// assert_eq!(reverse_map(1.0), (65535, 65535));
/// ```
pub fn reverse_map(n: f64) -> (u16, u16) {
    let index = (n * u32::MAX as f64) as u32;

    // deinterleave bits
    let mut x: u16 = 0;
    let mut y: u16 = 0;

    for i in 0..16 {
        // even bits -> x
        let x_bit = ((index >> (2 * i)) & 1) as u16;
        x |= x_bit << i;

        // odd bits -> y
        let y_bit = ((index >> (2 * i + 1)) & 1) as u16;
        y |= y_bit << i;
    }
    (x, y)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ex10::map;

    #[test]
    fn test_f_inverse_f() {
        // (f⁻¹ ∘ f)(x, y) = (x, y)
        // This is always perfect because every (x, y) is a valid input.
        let test_points = vec![
            (0, 0),
            (100, 200),
            (u16::MAX, u16::MAX),
            (12345, 54321),
            (1, 0),
            (0, 1),
        ];

        for (x, y) in test_points {
            let z = map(x, y);
            let (x_recovered, y_recovered) = reverse_map(z);

            assert_eq!(
                (x_recovered, y_recovered),
                (x, y),
                "Failed perfect identity for ({}, {})",
                x,
                y
            );
        }
    }

    #[test]
    fn test_f_of_f_inverse_exact() {
        // (f ∘ f⁻¹)(z) = z
        // We only test values that are DEFINED in the set A.
        // These are the exact results of mapping specific (x, y) pairs.
        let exact_values = vec![
            map(0, 0),         // 0.0
            map(65535, 65535), // 1.0
            map(100, 200),     // 0.000010762363674762278...
            map(1, 2),         // 0.0000000020954757933727176...
            map(12345, 54321), // 0.6528329410713243...
        ];

        for z in exact_values {
            let (x, y) = reverse_map(z);
            let z_recovered = map(x, y);

            // Since z was generated by map, it MUST be perfectly reversible
            // to the exact same bit pattern in f64.
            assert_eq!(
                z.to_bits(),
                z_recovered.to_bits(),
                "Bit-level mismatch for z = {}",
                z
            );
        }
    }

    #[test]
    fn test_dense_bijectivity() {
        // Checking every point in a 256x256 block to ensure no two points collide
        // and every point returns to its origin.
        for x in 0..256u16 {
            for y in 0..256u16 {
                let z = map(x, y);
                let (rx, ry) = reverse_map(z);
                assert_eq!((x, y), (rx, ry));
            }
        }
    }
}
